# Generated by Django 4.0.5 on 2022-06-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregable',
            name='entregado',
            field=models.BooleanField(null=b'I00\n'),
            preserve_default=b'I00\n',
        ),
    ]
